### ISSUE TITLE
Broken on Ubuntu due to missing libwebkitgtk

### ISSUE THREAD

**Issue by gdevenyi** [conda-forge/wxpython-feedstock#105]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Trying to use some features of wx from the conda-forge version on Ubuntu 18.04 fails with:

```
ImportError: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory
```

Somehow the build doesn't have all the dependencies.

Found in the context of psychopy.

### Installed packages

```shell
# packages in environment at /home/gdevenyi/mambaforge/envs/psychopy:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.9                hd590300_0    conda-forge
aom                       3.5.0                h27087fc_0    conda-forge
arabic_reshaper           2.1.4              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
atk-1.0                   2.38.0               hd4edc92_1    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
blosc                     1.21.4               h0f2a231_0    conda-forge
brotli                    1.0.9                h166bdaf_9    conda-forge
brotli-bin                1.0.9                h166bdaf_9    conda-forge
brotli-python             1.0.9            py38hfa26641_9    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
c-blosc2                  2.10.2               hb4ffafa_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cairo                     1.16.0            hbbf8b49_1016    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38h4a40e3a_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
configobj                 5.0.8              pyhd8ed1ab_0    conda-forge
configparser              5.3.0              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0            py38h7f3f72f_0    conda-forge
cryptography              41.0.3           py38hcdda232_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hd590300_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
distro                    1.8.0              pyhd8ed1ab_0    conda-forge
dukpy                     0.2.3            py38h0a891b7_3    conda-forge
esprima-python            4.0.1                   py_2001    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
ffmpeg                    5.1.2           gpl_hcbfe3e7_111    conda-forge
fluidsynth                2.3.3                h71480ea_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.42.1           py38h01eb140_0    conda-forge
freeglut                  3.2.2                hac7e632_2    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
freetype-py               2.4.0              pyhd8ed1ab_0    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gdk-pixbuf                2.42.10              h6b639ba_2    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gevent                    22.10.2          py38h0fd6f59_0    conda-forge
gitdb                     4.0.10             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.32             pyhd8ed1ab_0    conda-forge
glfw                      3.3.8                hd590300_1    conda-forge
glib                      2.76.4               hfc55251_0    conda-forge
glib-tools                2.76.4               hfc55251_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.7.8                hf3e180e_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
greenlet                  2.0.2            py38h17151c0_1    conda-forge
gst-plugins-base          1.22.5               hf7dbed1_0    conda-forge
gstreamer                 1.22.5               h98fc4e7_0    conda-forge
gtk2                      2.24.33              h90689f9_2    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
hdf5                      1.14.1          nompi_h4f84152_100    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imageio                   2.31.1             pyh24c5eb1_0    conda-forge
imageio-ffmpeg            0.4.8              pyhd8ed1ab_0    conda-forge
importlib-resources       6.0.1              pyhd8ed1ab_0    conda-forge
importlib_resources       6.0.1              pyhd8ed1ab_0    conda-forge
jack                      1.9.22               h0e77e87_1    conda-forge
jasper                    4.0.0                h32699f2_1    conda-forge
javascripthon             0.12               pyhd8ed1ab_0    conda-forge
json_tricks               3.17.3             pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py38h7f3f72f_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230125.3      cxx17_h59595ed_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libass                    0.17.1               hc9aadba_0    conda-forge
libavif                   0.11.1               h8182462_2    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcap                    2.69                 h0f662aa_0    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libclang                  15.0.7          default_h7634d5b_3    conda-forge
libclang13                15.0.7          default_h9986a30_3    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.2.1                hca28451_0    conda-forge
libdb                     6.2.32               h9c3ff4c_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libdrm                    2.4.114              h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.4               hebfc3b9_0    conda-forge
libglu                    9.0.0             hac7e632_1002    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libgpg-error              1.47                 h71f35ed_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
liblapacke                3.9.0           17_linux64_openblas    conda-forge
libllvm15                 15.0.7               h5cf9203_3    conda-forge
libmad                    0.15.1b           h0b41bf4_1001    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libopencv                 4.7.0            py38h498c9be_5    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpciaccess              0.17                 h166bdaf_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     15.4                 hfc447b1_0    conda-forge
libprotobuf               4.23.2               hd1fb520_5    conda-forge
libsndfile                1.2.2                hbc2eb40_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libsystemd0               254                  h3516f8a_0    conda-forge
libtasn1                  4.19.0               h166bdaf_0    conda-forge
libtiff                   4.5.1                h8b53f26_1    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.44.2               hd590300_1    conda-forge
libva                     2.19.0               hd590300_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libvpx                    1.13.0               hcb278e6_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxkbcommon              1.5.0                h5d7e998_3    conda-forge
libxml2                   2.11.5               h0d562d8_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
matplotlib                3.7.2            py38h578d9bd_0    conda-forge
matplotlib-base           3.7.2            py38hf5b0b65_0    conda-forge
moviepy                   1.0.3              pyhd8ed1ab_1    conda-forge
mpg123                    1.31.3               hcb278e6_0    conda-forge
msgpack-numpy             0.4.8              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.5            py38hfbd4bf9_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.33               hf1915f5_2    conda-forge
mysql-libs                8.0.33               hca2cd23_2    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
nettle                    3.8.1                hc379101_1    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.92                 h1d7d5a4_0    conda-forge
numexpr                   2.8.4           py38hb2af0cf_101    conda-forge
numpy                     1.24.4           py38h59b608b_0    conda-forge
opencv                    4.7.0            py38h578d9bd_5    conda-forge
openh264                  2.3.1                hcb278e6_2    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openpyxl                  3.1.2            py38h01eb140_0    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
opusfile                  0.12                 h3358134_2    conda-forge
p11-kit                   0.24.1               hc5aa10d_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3            py38hdc8b05c_1    conda-forge
pango                     1.50.14              heaa33ce_1    conda-forge
pathlib2                  2.3.7.post1      py38h578d9bd_2    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pillow                    10.0.0           py38h885162f_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
portaudio                 19.6.0               h0e77e87_8    conda-forge
portmidi                  2.0.4                h0e77e87_1    conda-forge
proglog                   0.1.9                      py_0    conda-forge
psutil                    5.9.5            py38h1de0b5d_0    conda-forge
psychopy                  2022.2.5         py38h578d9bd_1    conda-forge
psychtoolbox              3.0.19.0                 pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulseaudio-client         16.1                 hb77b528_4    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
py-opencv                 4.7.0            py38h0df68fb_5    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygame                    2.5.1            py38h3762873_0    conda-forge
pyglet                    1.5.27           py38h578d9bd_3    conda-forge
pyglfw                    2.6.2            py38h578d9bd_0    conda-forge
pyo                       1.0.5                    pypi_0    pypi
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyosf                     1.0.5                      py_2    conda-forge
pyparallel                0.2.2                    pypi_0    pypi
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pyqt                      5.15.9           py38hffdaa6c_4    conda-forge
pyqt5-sip                 12.12.2          py38h17151c0_4    conda-forge
pyserial                  3.5                pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pysoundfile               0.12.1             pyhd8ed1ab_0    conda-forge
pytables                  3.8.0            py38h5dedbee_2    conda-forge
python                    3.8.17          he550d4f_0_cpython    conda-forge
python-bidi               0.4.2                      py_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-gitlab             3.15.0             pyhd8ed1ab_0    conda-forge
python-sounddevice        0.4.6              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1            py38h01eb140_0    conda-forge
pyzmq                     25.1.1           py38h509eb50_0    conda-forge
qt-main                   5.15.8              h7fe3ca9_15    conda-forge
questplus                 2023.1             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
requests-toolbelt         1.0.0              pyhd8ed1ab_0    conda-forge
scipy                     1.10.1           py38h59b608b_3    conda-forge
sdl2                      2.26.5               h949db6a_0    conda-forge
sdl2_image                2.6.3                hd821750_1    conda-forge
sdl2_mixer                2.6.3                h563c3bf_0    conda-forge
sdl2_ttf                  2.20.2               h2123e47_1    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
sip                       6.7.11           py38h17151c0_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
svt-av1                   1.4.1                hcb278e6_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3.3            py38h01eb140_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
unicodedata2              15.0.0           py38h0a891b7_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
webassets                 2.0                        py_0    conda-forge
websocket-client          1.6.2              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
wxpython                  4.2.1            py38hb9b80a8_0    conda-forge
x264                      1!164.3095           h166bdaf_2    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xarray                    2023.1.0           pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xkeyboard-config          2.39                 hd590300_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxcursor           1.2.0                h0b41bf4_1    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxinerama          1.1.5                h27087fc_0    conda-forge
xorg-libxrandr            1.5.2                h7f98852_1    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-randrproto           1.5.0             h7f98852_1001    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zlib-ng                   2.0.7                h0b41bf4_0    conda-forge
zope.event                5.0                pyhd8ed1ab_0    conda-forge
zope.interface            6.0              py38h1de0b5d_0    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge
```

### Environment info

```shell
active environment : psychopy
    active env location : /home/gdevenyi/mambaforge/envs/psychopy
            shell level : 1
       user config file : /home/gdevenyi/.condarc
 populated config files : /home/gdevenyi/mambaforge/.condarc
                          /home/gdevenyi/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __glibc=2.27=0
                          __linux=5.4.0=0
                          __unix=0=0
       base environment : /home/gdevenyi/mambaforge  (writable)
      conda av data dir : /home/gdevenyi/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nvidia/linux-64
                          https://conda.anaconda.org/nvidia/noarch
                          https://conda.anaconda.org/rapidsai/linux-64
                          https://conda.anaconda.org/rapidsai/noarch
                          https://conda.anaconda.org/simpleitk/linux-64
                          https://conda.anaconda.org/simpleitk/noarch
                          https://conda.anaconda.org/mrtrix3/linux-64
                          https://conda.anaconda.org/mrtrix3/noarch
                          https://conda.anaconda.org/itk/linux-64
                          https://conda.anaconda.org/itk/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/gdevenyi/mambaforge/pkgs
                          /home/gdevenyi/.conda/pkgs
       envs directories : /home/gdevenyi/mambaforge/envs
                          /home/gdevenyi/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.9.16 Linux/5.4.0-150-generic neon/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by psobolewskiPhD** [comment]
I also ran into this. Traceback:
```
Traceback (most recent call last):
  File "/opt/conda/envs/cellprofiler/lib/python3.8/site-packages/cellprofiler/gui/help/menu.py", line 21, in <lambda>
    event_fn=lambda _: self.frame.show_welcome_screen(True),
  File "/opt/conda/envs/cellprofiler/lib/python3.8/site-packages/cellprofiler/gui/cpframe.py", line 460, in show_welcome_screen
    from ._welcome_frame import WelcomeFrame
  File "/opt/conda/envs/cellprofiler/lib/python3.8/site-packages/cellprofiler/gui/_welcome_frame.py", line 9, in <module>
    import wx.html2
  File "/opt/conda/envs/cellprofiler/lib/python3.8/site-packages/wx/html2.py", line 15, in <module>
    from ._html2 import *
ImportError: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/conda/envs/cellprofiler/lib/python3.8/site-packages/cellprofiler/gui/help/menu.py", line 21, in <lambda>
    event_fn=lambda _: self.frame.show_welcome_screen(True),
  File "/opt/conda/envs/cellprofiler/lib/python3.8/site-packages/cellprofiler/gui/cpframe.py", line 460, in show_welcome_screen
    from ._welcome_frame import WelcomeFrame
  File "/opt/conda/envs/cellprofiler/lib/python3.8/site-packages/cellprofiler/gui/_welcome_frame.py", line 9, in <module>
    import wx.html2
  File "/opt/conda/envs/cellprofiler/lib/python3.8/site-packages/wx/html2.py", line 15, in <module>
    from ._html2 import *
ImportError: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory
```
micromamba info:
```
       libmamba version : 1.5.0
     micromamba version : 1.5.0
           curl version : libcurl/7.88.1 OpenSSL/3.1.2 zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       envs directories : /home/sobolp.linux/micromamba/envs
          package cache : /home/sobolp.linux/micromamba/pkgs
                          /home/sobolp.linux/.mamba/pkgs
            environment : None (not found)
           env location : -
      user config files : /home/sobolp.linux/.mambarc
 populated config files : 
       virtual packages : __unix=0=0
                          __linux=5.15.0=0
                          __glibc=2.35=0
                          __archspec=1=x86_64
               channels : 
       base environment : /home/sobolp.linux/micromamba
               platform : linux-64

```

doesn't happen with the same install on macOS.
