### ISSUE TITLE
Incompatible with wxWidgets 3.2.6 on 64-bit Windows

### ISSUE THREAD

**Issue by QuLogic** [conda-forge/wxpython-feedstock#125]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

With micromamba on a 64-bit Windows, creating a bare environment with just wxPython:
```
micromamba env create -n wx-test python=3.12 wxpython
```
then running a simple import:
```
micromamba activate wx-test
python
>>> import wx
```
fails to load due to a missing DLL:
``` 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Elliott\micromamba\envs\wx-test\Lib\site-packages\wx\__init__.py", line 17, in <module>
    from wx.core import *
  File "C:\Users\Elliott\micromamba\envs\wx-test\Lib\site-packages\wx\core.py", line 12, in <module>
    from ._core import *
ImportError: DLL load failed while importing _core: The specified module could not be found.
```
The same thing happens with the demo:
```
> wxdemo
Traceback (most recent call last):
  File "\\?\C:\Users\Elliott\micromamba\envs\wx-test\Scripts\wxdemo-script.py", line 33, in <module>
    sys.exit(load_entry_point('wxPython==4.2.1', 'console_scripts', 'wxdemo')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\Elliott\micromamba\envs\wx-test\Scripts\wxdemo-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elliott\micromamba\envs\wx-test\Lib\importlib\metadata\__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elliott\micromamba\envs\wx-test\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Elliott\micromamba\envs\wx-test\Lib\site-packages\wx\__init__.py", line 17, in <module>
    from wx.core import *
  File "C:\Users\Elliott\micromamba\envs\wx-test\Lib\site-packages\wx\core.py", line 12, in <module>
    from ._core import *
ImportError: DLL load failed while importing _core: The specified module could not be found.
```

Looking at the `_core.cp312-win_amd64.pyd` in Dependencies shows that it is looking for `wxbase32u_vc.dll`, `wxbase32u_net_vc.dll`, and `wxmsw32u_core_vc.dll`, which cannot be found.

Looking at the environment's `Library\bin` directory, there are the files: `wxbase32u_vc_x64.dll`, `wxbase32_u_net_vc_x64.dll`, and `wxmsw32u_core_vc_x64.dll`. If you copy these files without the `_x64` suffix, then everything works.

Also, if you downgrade wxwidgets to 3.2.5, everything works.

### Installed packages

```shell
List of packages in environment: "C:\\Users\\Elliott\\micromamba\\envs\\wx-test"

  Name             Version                Build               Channel
---------------------------------------------------------------------------
  _openmp_mutex    4.5                    2_gnu               conda-forge
  bzip2            1.0.8                  h2466b09_7          conda-forge
  ca-certificates  2024.8.30              h56e8100_0          conda-forge
  freetype         2.12.1                 hdaf720e_2          conda-forge
  intel-openmp     2024.2.1               h57928b3_1083       conda-forge
  lcms2            2.16                   h67d730c_0          conda-forge
  lerc             4.0.0                  h63175ca_0          conda-forge
  libblas          3.9.0                  24_win64_mkl        conda-forge
  libcblas         3.9.0                  24_win64_mkl        conda-forge
  libdeflate       1.21                   h2466b09_0          conda-forge
  libexpat         2.6.3                  he0c23c2_0          conda-forge
  libffi           3.4.2                  h8ffe710_5          conda-forge
  libgcc           14.1.0                 h1383e82_1          conda-forge
  libgomp          14.1.0                 h1383e82_1          conda-forge
  libjpeg-turbo    3.0.0                  hcfcfb64_1          conda-forge
  liblapack        3.9.0                  24_win64_mkl        conda-forge
  libpng           1.6.44                 h3ca93ac_0          conda-forge
  libsqlite        3.46.1                 h2466b09_0          conda-forge
  libtiff          4.6.0                  hb151862_4          conda-forge
  libwebp-base     1.4.0                  hcfcfb64_0          conda-forge
  libwinpthread    12.0.0.r4.gg4f2fc60ca  h57928b3_8          conda-forge
  libxcb           1.17.0                 h0e4246c_0          conda-forge
  libzlib          1.3.1                  h2466b09_1          conda-forge
  mkl              2024.1.0               h66d3029_694        conda-forge
  numpy            2.1.1                  py312h49bc9c5_0     conda-forge
  openjpeg         2.5.2                  h3d672ee_0          conda-forge
  openssl          3.3.2                  h2466b09_0          conda-forge
  pcre2            10.44                  h3d7b363_2          conda-forge
  pillow           10.4.0                 py312h381445a_1     conda-forge
  pip              24.2                   pyh8b19718_1        conda-forge
  pthread-stubs    0.4                    h0e40799_1002       conda-forge
  [1m[34mpython         [0m  3.12.6                 hce54a09_2_cpython  conda-forge
  python_abi       3.12                   5_cp312             conda-forge
  setuptools       75.1.0                 pyhd8ed1ab_0        conda-forge
  six              1.16.0                 pyh6c4a22f_0        conda-forge
  tbb              2021.7.0               h91493d7_0          conda-forge
  tk               8.6.13                 h5226925_1          conda-forge
  tzdata           2024a                  h8827d51_1          conda-forge
  ucrt             10.0.22621.0           h57928b3_0          conda-forge
  vc               14.3                   h8a93ad2_21         conda-forge
  vc14_runtime     14.40.33810            ha82c5b3_21         conda-forge
  vs2015_runtime   14.40.33810            h3bf8584_21         conda-forge
  wheel            0.44.0                 pyhd8ed1ab_0        conda-forge
  [1m[34mwxpython       [0m  4.2.1                  py312h649c44c_6     conda-forge
  wxwidgets        3.2.6                  had4d501_0          conda-forge
  xorg-libxau      1.0.11                 h0e40799_1          conda-forge
  xorg-libxdmcp    1.1.5                  h0e40799_0          conda-forge
  xz               5.2.6                  h8d14728_0          conda-forge
  zstd             1.5.6                  h0ea2cb4_0          conda-forge
```

### Environment info

```shell
micromamba info

       libmamba version : 1.5.10
     micromamba version : 1.5.10
           curl version : libcurl/8.2.1-DEV Schannel zlib/1.2.13
     libarchive version : libarchive 3.6.2 zlib/1.2.13 liblzma/5.4.3 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.5
       envs directories : C:\Users\Elliott\micromamba\envs
          package cache : C:\Users\Elliott\micromamba\pkgs
                          C:\Users\Elliott\.mamba\pkgs
                          C:\Users\Elliott\AppData\Roaming\.mamba\pkgs
            environment : wx-test (active)
           env location : C:\Users\Elliott\micromamba\envs\wx-test
      user config files : C:\Users\Elliott\.mambarc
 populated config files : C:\Users\Elliott\.condarc
       virtual packages : __win=0=0
                          __archspec=1=x86_64
               channels : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : C:\Users\Elliott\micromamba
               platform : win-64
```

**Comment by bkpoon** [comment]
I have the same issue on macOS (Intel and Apple Silicon). It looks like `wxPython` is expecting a file like `libwx_osx_cocoau_core-3.2.0.2.3.dylib` from `wxwidgets=3.2.5` which does not exist in `wxwidgets=3.2.6`. There is `libwx_osx_cocoau_core-3.2.0.3.0.dylib` instead. I'm guessing a rebuilding of this feedstock should fix the problem. There is a pinning for `wxwidgets` in `conda-forge-pinning`, but it is only at `3.2` which would not catch this change.

**Comment by pauldmccarthy** [comment]
Yes, the current wxpython (4.2.1) is incompatible with the new wxwidgets (3.2.6). A temporary work-around is to pin wxwidgets at 3.2.5. I think the safest option until this is resolved is to pin the wxwidgets version that is used at the time that the wxpython package is built, so I'll do that shortly.

I've not looked into it further, but my suspicion is that this is due to a step in the wxwidgets build process, which I've described at conda-forge/wxwidgets-feedstock#48, which causes the compiled wxpython libraries to link against the wrong wxwidgets library files. I'm waiting to hear back from the wxwidgets conda-forge maintainers before contacting the wxwidgets developers directly.

**Comment by pauldmccarthy** [comment]
Given that I'm (hopefully) about to publish wxpython 4.2.2, I won't bother rebuilding 4.2.1 with the pinning constraint, unless anybody has a specific need for that version?

**Comment by pauldmccarthy** [comment]
@QuLogic @bkpoon wxpython 4.2.2 has been published - I've performed a rudimentary test on macOS (intel), and it appears to be working. Can you check whether it works for you?

I've adjusted the wxpython recipe so that it requires wxwigets 3.2.6, so there should be no chance of a different (incompatible) version being installed.

**Comment by bkpoon** [comment]
I just tested wxpython 4.2.2 with wxwidgets 3.2.6 and it works for me. I also tried installing wxwidgets 3.2.5 with wxpython 4.2.2 and conda does complain so the pinning does work. Thanks!

**Comment by QuLogic** [comment]
Yes, it has worked on Windows as well with wxWidgets 3.2.6 and wxPython 4.2.2.
