### ISSUE TITLE
Mac Build Failing

### ISSUE THREAD

**Issue by scopatz** [conda-forge/wxpython-feedstock#15]
Just tried building the current master (30214f843b44442c2f3db660e1f117e5ce18689a) on my current mac cloud and got the following error:

```
/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/build/wxbld/bk-deps clang++ -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.6 -c -o netdll_protocol.o -I./.pch/wxprec_netdll -D__WXOSX_COCOA__      -DWXBUILDING -I/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/build/wxbld/src/tiff/libtiff -I/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/ext/wxWidgets/src/tiff/libtiff -I/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/ext/wxWidgets/src/jpeg -I/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/ext/wxWidgets/src/png  -I/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/ext/wxWidgets/src/regex  -DwxUSE_GUI=0 -DWXUSINGDLL -DWXMAKINGDLL_NET -dynamic -fPIC -DPIC -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -Wno-deprecated-declarations -D_FILE_OFFSET_BITS=64 -I/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/build/wxbld/lib/wx/include/osx_cocoa-unicode-3.0 -I/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/ext/wxWidgets/include -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 -I/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -DWX_PRECOMP -O2 -fno-strict-aliasing -mmacosx-version-min=10.9 -stdlib=libc++ -m64 -fno-common -fvisibility=hidden -fvisibility-inlines-hidden /Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/ext/wxWidgets/src/common/protocol.cpp
1 error generated.
make: *** [basedll_cocoa_utils.o] Error 1
make: *** Waiting for unfinished jobs....
Error building
ERROR: failed building wxWidgets
Traceback (most recent call last):
  File "build.py", line 1295, in cmd_build_wx
    wxbuild.main(wxDir(), build_options)
  File "/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/buildtools/build_wxwidgets.py", line 498, in main
    exitIfError(wxBuilder.build(dir=buildDir, options=args), "Error building")
  File "/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/buildtools/build_wxwidgets.py", line 85, in exitIfError
    raise builder.BuildError(msg)
buildtools.builder.BuildError: Error building
Finished command: build_wx (7m2.759s)
Finished command: build (7m2.761s)
WARNING: Building this way assumes that all generated files have been 
generated already.  If that is not the case then use build.py directly 
to generate the source and perform the build stage.  You can use 
--skip-build with the bdist_* or install commands to avoid this 
message and the wxWidgets and Phoenix build steps in the future.

"/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python" -u build.py build
Command '"/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python" -u build.py build' failed with exit code 1.
Traceback (most recent call last):
  File "/Users/anthony/miniconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/anthony/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/anthony/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/anthony/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/anthony/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 2097, in build_tree
    notest=notest,
  File "/Users/anthony/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1370, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/Users/anthony/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 294, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/anthony/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 273, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/anthony/miniconda/conda-bld/wxpython_1521647577133/work/conda_build.sh']' returned non-zero exit status 1.
```

Any ideas?

**Comment by Korijn** [comment]
Take a deep breath and dive in...

**Comment by scopatz** [comment]
Haha, well, if there is a PR that someone wants me to try, I am happy to help out in that way.

**Comment by ChrisBarker-NOAA** [comment]
Fails for me too -- looks like this is the actual failure:

```
In file included from /Users/Chris/miniconda3/conda-bld/wxpython_1521673702151/work/ext/wxWidgets/include/wx/string.h:46:
/Users/Chris/miniconda3/conda-bld/wxpython_1521673702151/work/ext/wxWidgets/include/wx/strvararg.h:25:14: fatal error: 'type_traits' file not found
    #include <type_traits>
             ^~~~~~~~~~~~~
```

looks like there is stuff on build.sh that is supposed to correct that :-(

I'm trying outside conda-build now -- hasn't crashed yet....


no idea what/where type_traits is..... I'll do a bit of research.

@scopatz: is that where it fails for you, too?

-CHB

**Comment by ChrisBarker-NOAA** [comment]
OK:

a plain python setup.py build

worked fine on my machine, but when I tried to do that inside conda-build, I got the same failure:

```
/Users/Chris/miniconda3/conda-bld/wxpython_1521677390646/work/ext/wxWidgets/include/wx/strvararg.h:25:14: fatal error: 'type_traits' file not found
    #include <type_traits>
```
This is OS-X 10.13
$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)

So what's different about how conda-build sets things up???

**Comment by ocefpaf** [comment]
I believe that was fixed. Please re-open if it is still relevant.
