### ISSUE TITLE
Import wx.lib.pubsub fails on linux

### ISSUE THREAD

**Issue by constantinpape** [conda-forge/wxpython-feedstock#25]
Issue:

Importing `wx.lib.pubsub` fails on linux (ubuntu 16.04) with the following exception:
```
Traceback (most recent call last):
  File "/home/cpape/Work/software/conda/miniconda3/envs/wxp/lib/python3.7/site-packages/wx/lib/pubsub/__init__.py", line 38, in <module>
    from pubsub import *
ModuleNotFoundError: No module named 'pubsub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cpape/Work/software/conda/miniconda3/envs/wxp/lib/python3.7/site-packages/wx/lib/pubsub/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Stand-alone pubsub not found. Use `pip install PyPubSub`
```

Conda environment:
```
$ conda list
# packages in environment at /home/cpape/Work/software/conda/miniconda3/envs/wxp:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py37_1003    conda-forge
atk                       2.25.90              h05f3006_1    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12              h276e583_5    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
cffi                      1.11.5           py37h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
cryptography              2.3.1            py37hdffb7b8_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
gdk-pixbuf                2.36.12              h4ab6910_1    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
gobject-introspection     1.56.1           py37haaf12d0_1    conda-forge
graphite2                 1.3.13               hfc679d8_0    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h5856ed1_0    conda-forge
gtk2                      2.24.31              hde048ef_0    conda-forge
harfbuzz                  1.9.0                h04dbb29_1    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libglu                    9.0.0                hfc679d8_0    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.36               ha92aebf_0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.10               he6b73bb_1    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
ncurses                   6.1                  hfc679d8_2    conda-forge
openssl                   1.0.2p               h470a237_2    conda-forge
pango                     1.40.14              he752989_2    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pip                       18.1                  py37_1000    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                py37_1000    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
python                    3.7.1                h5001a0f_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.21.0                py37_1000    conda-forge
setuptools                40.6.3                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0               hb1c47c0_0    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wheel                     0.32.3                   py37_0    conda-forge
wxpython                  4.0.3            py37hd2a7a6d_2    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

```
$ conda info
     active environment : wxp
    active env location : /home/cpape/Work/software/conda/miniconda3/envs/wxp
            shell level : 1
       user config file : /home/cpape/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /home/cpape/Work/software/conda/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/cpape/Work/software/conda/miniconda3/pkgs
                          /home/cpape/.conda/pkgs
       envs directories : /home/cpape/Work/software/conda/miniconda3/envs
                          /home/cpape/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.15.0-43-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by constantinpape** [comment]
I have made a PR to add pypubsub:
https://github.com/conda-forge/staged-recipes/pull/7531
Once this is added; including this as dependency here should fix this issue.

**Comment by constantinpape** [comment]
pypubsub is on conda-forge now.
I suggest adding it to the dependencies to fix this issue.
I don't know whether this is necessary for linux only or for all OS.

**Comment by ocefpaf** [comment]
Do you want to send a PR adding the `wx.lib.pubsub` to the tests and checking what fails and then adding the new dependency to the platforms that may need it?

**Comment by ocefpaf** [comment]
Done in #26.
